import { Injectable, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Injectable({
    providedIn: 'root',
})
export class Audio {
    private ctx: AudioContext | null = null;
    private platformId = inject(PLATFORM_ID);

    /**
     * `getContext`
     *
     * Returns a singleton instance of AudioContext.
     * This is a better approach to use the constructor to get the context.
     *
     * @returns {AudioContext | null}
     */
    private getContext(): AudioContext | null {
        if (!isPlatformBrowser(this.platformId)) return null;

        if (this.ctx) return this.ctx;

        this.ctx = new (window.AudioContext || (window as any).webkitAudioContext)();
        return this.ctx;
    }

    // The code below was almost entirely generated by AI.
    // I don't know how to make plim plim plim plom sounds.
    playClick() {
        const context = this.getContext();
        if (!context) return;

        if (context.state === 'suspended') context.resume();

        const osc = context.createOscillator();
        const gain = context.createGain();

        osc.connect(gain);
        gain.connect(context.destination);

        osc.type = 'sine';
        osc.frequency.setValueAtTime(600, context.currentTime);
        osc.frequency.exponentialRampToValueAtTime(100, context.currentTime + 0.05);

        gain.gain.setValueAtTime(0.3, context.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.05);

        osc.start();
        osc.stop(context.currentTime + 0.05);
    }

    playGhibliAlert() {
        const context = this.getContext();
        if (!context) return;

        if (context.state === 'suspended') context.resume();

        const masterGain = context.createGain();
        masterGain.connect(context.destination);

        masterGain.gain.setValueAtTime(0, context.currentTime);
        masterGain.gain.linearRampToValueAtTime(0.3, context.currentTime + 4.0);

        const notes = [
            349.23, 440.0, 523.25, 659.25, 392.0, 493.88, 587.33, 783.99, 659.25, 523.25, 440.0,
            349.23,
        ];

        let startTime = context.currentTime;

        const gapBetweenNotes = 0.5;
        const noteSustain = 4.5;

        notes.forEach((freq, index) => {
            const osc = context.createOscillator();
            const noteGain = context.createGain();

            osc.connect(noteGain);
            noteGain.connect(masterGain);

            osc.type = 'sine';
            osc.frequency.value = freq;

            const noteTime = startTime + index * gapBetweenNotes;

            noteGain.gain.setValueAtTime(0, noteTime);
            noteGain.gain.linearRampToValueAtTime(0.8, noteTime + 0.05);

            noteGain.gain.exponentialRampToValueAtTime(0.001, noteTime + noteSustain);

            osc.start(noteTime);
            osc.stop(noteTime + noteSustain);
        });
    }
}
